### ISSUE TITLE
esl-erlang or erlang?

### ISSUE THREAD

**Issue by stevecstian** [chef-cookbooks/erlang#22]
Which package should be installed when we choose `esl` as `install_method`?  

For `v1.5.6` release:
- `esl-erlang` will be installed for `debian`
- `erlang` will be installed for `rhel`

Is this expected?

**Comment by jennyfountain** [comment]
This is causing an issue for me. I used the esl package install method in 1.3.1 and now it's trying to install erlang not install esl-erlang or upgrade esl-erlang.  Is this a mistake?

**Comment by jennyfountain** [comment]
dump

**Comment by cmluciano** [comment]
I commented on #28 and am posting here for more input from steve also.

I'm a little iffy on this, as in I'm trying to determine the proper approach. Comparing the two packages, it seems that the erlang package just provides language & runtime. The esl-erlang package contains "more packages", but I cannot determine which other packages they are.

I asked in the Erlang IRC channel and poked around the erlang-solutions site to no avail. Can you please help me to understand the difference?

That said, I agree that if I choose the ESL recipe, I should expect that the ESL package is installed.

**Comment by jtimberman** [comment]
When using the Erlang Solutions repository, the difference between `erlang` and `esl-erlang` is the way the packaging is done. With `erlang`, the various erlang "apps" are split up in separate packages, whereas with `esl-erlang` they are all included in a single package.

After installing `erlang` from the Erlang Solutions repository, this file exists:

- /usr/lib64/erlang/releases/17/installed_application_versions

After installing `esl-erlang`, the same content contents are in:

- /usr/lib/erlang/releases/17/installed_application_versions

These files have the same packages and versions. So the question is, would it be less surprising to have a single package that includes everything or separate packages for every thing? IMO, we should err on the side of using the single package, because we're not allowing customization of the package name in this recipe.

**Comment by jtimberman** [comment]
Using `esl-erlang` also may fix #9, though we probably should check with @jjasghar to see if there's currently issues with the RabbitMQ cookbook, as #9 was opened a couple years ago now.

**Comment by jennyfountain** [comment]
Thanks @jtimberman

**Comment by cmluciano** [comment]
@jtimberman Thanks for clearing that up. Do you think having the different recipes for each package makes sense?

Also @jjasghar I don't believe that we are currently facing issues with the rabbitmq erlang version right?

**Comment by jjasghar** [comment]
@cmluciano i'm like 95% sure we aren't facing anything with pkg installs. We've written some code around it to try to pull the correct thing down. I think if we can get it upstream with the erlang cookbook it'll help simplify anyone relying on this cookbook.

**Comment by jennyfountain** [comment]
Having the option to install esl-erlang is necessary for us since we already use esl-erlang in our environment. Otherwise, we need to redo our entire rabbitmq cluster to use erlang (if we keep using the community rabbitmq cookbook) or rewrite our rabbitmq wrapper cookbook to not use the rabbitmq community cookbook since it uses erlang and there is no way around that.

**Comment by cheeseplus** [comment]
This doesn't appear to a problem with #29 which separates out the ESL recipes as it's own standalone. Is there still a dependency issue with rabbtimq here?

**Comment by cheeseplus** [comment]
Closing out given no further responses and that is appears resolved.
